print("\nOlá, Mundo!")
msg = 'Iniciando os estudos da linguagem Python.'
print("~"*41)
print(msg)
print("~"*41)
print("Estudante: Erick A. I. Souza")
print("Data: 24/10/2021")
print("Idade: 27")
print("Curso Superior: ADS")
print("Objetivo: Data science e Machine learning")
print("-"*41)
print("Versão: Python 3.11.0")
print("IDE: Pycharm")
print("OS: Windows 10")
print("-"*41)
print("Professor: Gustavo Guanabara")
print("Planataforma: YouTube")
print("Canal: Curso em Vídeo")
print("Livro: Indrodução à programação com Python")
print("-"*41)
